### ISSUE TITLE
Lariat takes a long time

### ISSUE THREAD

**Issue by dcopetti** [10XGenomics/lariat#12]
Hello,

I am wondering if it is normal that longranger wgs (in the lariat step) is taking a long time to complete: it is now going on since two weeks.
This is the command:
`longranger wgs --id=lngrgrwgs_to_NRG --fastqs=../input_fastqs --reference=refdata-genome_for_longranger --vcmode=freebayes --somatic --localcores=8 --localmem=70 --sex=f`
The input files are 150 GB (two lanes of 33-37 GB each with 2.5 GB I1.fq.gz file), the reference is 4.5 Gb and has been formatted (number of sequences, max sequence length) to fit `longranger mkref` requirements. The output is 1.4 TB now, the stdout shows
`2018-03-06 00:03:45 [runtime] (run:local)       ID.lngrgrwgs_to_NRG.PHASER_SVCALLER_CS.PHASER_SVCALLER._LINKED_READS_ALIGNER.BARCODE_AWARE_ALIGNER.fork0.chnk127.main`
only the _log file and the journal folder (which is empty) are being updated. Htop shows that there are 8 jobs running. The _log file shows
`2018-03-19 05:17:48 [jobmngr] Attempted to reserve 4 threads, but only 0 were available.`

Is this a normal computation time for this process?
Thanks,
Dario

**Comment by wheaton5** [comment]
I don't think this is normal although you are running it in a way I rarely do (locally with not that many cores). I would ping @ablewhiskey and @pmarks. With 8 cores given to longranger it should only be able to run 2 (4 with hyperthreading? not sure) chunks of Lariat at a time since each one requests 4 threads. So I'm a bit confused why it says 8 jobs are running. Also are those jobs taking up good amount of CPU? Not sure what the error about 0 threads being available means. I think Alex would be the best one to answer that. Also you can email support@10xgenomics.com for a more formal support ticket. In general Lariat should be about 15-20% slower than bwa mem so that should give you an idea of the expected runtime.

**Comment by adam-azarchs** [comment]
The 0 threads message is meaningless.  As Haynes said, are those running jobs using CPU?  2 weeks is a long time.  It's possible they're hanging on I/O.  For a more complete analysis you should upload a problem report with `longranger upload` so that the support team has (hopefully) all the information relevant to diagnosing your problem.

**Comment by dcopetti** [comment]
Thank you both for the suggestions!
The run eventually completed yesterday, and the output folder looks like this:
```
-rw-r--r-- 1 copettid mpb  91K Mar  2 08:53 _mrosource
-rw-r--r-- 1 copettid mpb    5 Mar  2 08:53 _jobmode
-rw-r--r-- 1 copettid mpb  827 Mar  2 08:53 _invocation
-rw-r--r-- 1 copettid mpb   58 Mar  2 08:53 _versions
-rw-r--r-- 1 copettid mpb   36 Mar  2 08:53 _uuid
-rw-r--r-- 1 copettid mpb   26 Mar  2 08:53 _timestamp
-rw-r--r-- 1 copettid mpb    2 Mar  2 08:53 _tags
drwxr-xr-x 4 copettid mpb 4.0K Mar  2 08:53 PHASER_SVCALLER_CS
drwxr-xr-x 2 copettid mpb 4.0K Mar  2 08:53 tmp
-rw-r--r-- 1 copettid mpb  232 Mar  2 09:59 _cmdline
-rw-r--r-- 1 copettid mpb  12K Mar  2 09:59 _sitecheck
-rw-r--r-- 1 copettid mpb  21K Mar  2 09:59 _filelist
-rw-r--r-- 1 copettid mpb  31K Mar  2 09:59 lngrgrwgs_to_NRG.mri.tgz
-rw-r--r-- 1 copettid mpb   19 Mar  5 10:13 _lock
-rw-r--r-- 1 copettid mpb 102K Mar 19 11:24 _log
drwxr-xr-x 2 copettid mpb  12K Mar 19 13:39 journal
```
which I see is different from what I should expect. The total size is 1.4 TB, I uploaded the _log file and I am in contact with 10X support.
Next time I will run one lane instead of two: how should I specify the `--lanes=` parameter? my fastq files are named 4606-KCB-0001_S6_L006_[I/R]1_001.fastq.gz. is it just `--lanes=L006`?
Thanks,
Dario

**Comment by adam-azarchs** [comment]
I believe 10X support is looking into your case now, so I'm closing this issue.

For anyone else watching this issue, it appears that each chunk was taking around 6 hours, which is a long time but not totally unreasonable for a very large data set, but also `--localcores` and `--localmem` were set such that only two chunks at a time could run in parallel.  The version of the [pipeline management system](http://martian-lang.org) bundled with Longeranger 2.2.0 (released just a few days ago, yay!) would make it much more obvious in the logs that progress was actually being made, albeit slowly.
